/**
 * Represents a generic object for analytics properties, allowing various primitive types,
 * arrays of primitives, or nested objects/arrays of objects.
 */
export type AnalyticsProperties = {
  [key: string]:
    | string
    | number
    | boolean
    | null
    | undefined
    | Array<string | number | boolean | null | undefined>
    | AnalyticsProperties
    | Array<AnalyticsProperties>;
};

/**
 * Common analytics event names.
 */
export type AnalyticsEventName =
  | 'page_view'
  | 'click'
  | 'form_submit'
  | 'search'
  | 'add_to_cart'
  | 'remove_from_cart'
  | 'checkout_started'
  | 'purchase'
  | 'sign_up'
  | 'login'
  | 'logout'
  | 'error'
  | 'custom_event';

/**
 * Base interface for any analytics event.
 */
export interface BaseAnalyticsEvent {
  /**
   * The name of the analytics event.
   */
  name: AnalyticsEventName | string;
  /**
   * A unique identifier for the event. If not provided, one might be generated by the client.
   */
  eventId?: string;
  /**
   * The timestamp when the event occurred.
   * Can be an ISO 8601 string (e.g., "2023-10-27T10:00:00.000Z") or milliseconds since epoch.
   */
  timestamp: string | number;
  /**
   * Properties associated with the event.
   */
  properties?: AnalyticsProperties;
}

/**
 * Properties specific to a 'page_view' event.
 */
export interface PageViewEventProperties extends AnalyticsProperties {
  /**
   * The full URL of the page.
   */
  url: string;
  /**
   * The path of the page (e.g., '/products/item-123').
   */
  path: string;
  /**
   * The title of the page.
   */
  title?: string;
  /**
   * The referrer URL.
   */
  referrer?: string;
  /**
   * The hostname of the page.
   */
  hostname?: string;
  /**
   * The query string of the URL.
   */
  queryString?: string;
}

/**
 * Properties specific to a 'click' event.
 */
export interface ClickEventProperties extends AnalyticsProperties {
  /**
   * The ID of the clicked HTML element, if available.
   */
  element_id?: string;
  /**
   * The text content of the clicked element.
   */
  element_text?: string;
  /**
   * The tag name of the clicked element (e.g., 'BUTTON', 'A', 'DIV').
   */
  element_tag?: string;
  /**
   * The CSS selector path to the clicked element.
   */
  element_selector?: string;
  /**
   * The URL or href attribute of the clicked element, if applicable.
   */
  target_url?: string;
}

/**
 * Properties specific to a 'form_submit' event.
 */
export interface FormSubmitEventProperties extends AnalyticsProperties {
  /**
   * The ID of the submitted form.
   */
  form_id?: string;
  /**
   * The name of the submitted form.
   */
  form_name?: string;
  /**
   * The URL where the form was submitted.
   */
  form_url?: string;
  /**
   * An array of field names that were part of the form submission.
   */
  fields?: string[];
  /**
   * Indicates if the form submission was successful.
   */
  success?: boolean;
}

/**
 * Properties for an individual item in an e-commerce event (e.g., add_to_cart, purchase).
 */
export interface ProductItemProperties extends AnalyticsProperties {
  /**
   * The unique ID of the product.
   */
  product_id: string;
  /**
   * The name of the product.
   */
  product_name?: string;
  /**
   * The price of a single unit of the product.
   */
  price?: number;
  /**
   * The quantity of the product.
   */
  quantity: number;
  /**
   * The currency of the price (e.g., 'USD', 'EUR').
   */
  currency?: string;
  /**
   * The category of the product.
   */
  category?: string;
  /**
   * The brand of the product.
   */
  brand?: string;
  /**
   * The variant of the product (e.g., 'red', 'large').
   */
  variant?: string;
}

/**
 * Properties specific to an 'add_to_cart' event.
 */
export interface AddToCartEventProperties extends AnalyticsProperties {
  /**
   * The ID of the product added to the cart.
   */
  product_id: string;
  /**
   * The name of the product.
   */
  product_name?: string;
  /**
   * The price of the product.
   */
  price?: number;
  /**
   * The quantity added.
   */
  quantity: number;
  /**
   * The currency of the price (e.g., 'USD', 'EUR').
   */
  currency?: string;
  /**
   * The category of the product.
   */
  category?: string;
  /**
   * An array of items added to the cart (useful for adding multiple items at once).
   */
  items?: ProductItemProperties[];
}

/**
 * Properties specific to a 'purchase' event.
 */
export interface PurchaseEventProperties extends AnalyticsProperties {
  /**
   * The unique ID of the transaction or order.
   */
  transaction_id: string;
  /**
   * The total revenue of the purchase.
   */
  revenue: number;
  /**
   * The currency of the revenue.
   */
  currency: string;
  /**
   * The tax amount.
   */
  tax?: number;
  /**
   * The shipping cost.
   */
  shipping?: number;
  /**
   * The coupon code used for the purchase.
   */
  coupon?: string;
  /**
   * An array of items purchased.
   */
  items: ProductItemProperties[];
}

/**
 * Represents a user for identification purposes.
 */
export interface AnalyticsUser {
  /**
   * A unique identifier for the user. This is typically a stable ID that persists across sessions.
   */
  id: string;
  /**
   * The user's email address.
   */
  email?: string;
  /**
   * The user's full name.
   */
  name?: string;
  /**
   * Any additional custom properties for the user (e.g., 'plan', 'subscription_status').
   */
  properties?: AnalyticsProperties;
}

/**
 * Represents the global context for analytics events.
 * This data is typically sent with every event or batch of events.
 */
export interface AnalyticsContext {
  /**
   * The user agent string of the client.
   */
  userAgent?: string;
  /**
   * The IP address of the client.
   */
  ipAddress?: string;
  /**
   * The screen resolution (e.g., '1920x1080').
   */
  screenResolution?: string;
  /**
   * The viewport dimensions (e.g., '1024x768').
   */
  viewport?: string;
  /**
   * The language setting of the client (e.g., 'en-US').
   */
  language?: string;
  /**
   * The current timezone of the client.
   */
  timezone?: string;
  /**
   * The current URL of the page.
   */
  pageUrl?: string;
  /**
   * The referrer URL.
   */
  referrer?: string;
  /**
   * A unique identifier for the current session.
   */
  sessionId?: string;
  /**
   * Any additional custom context properties.
   */
  custom?: AnalyticsProperties;
}

/**
 * A discriminated union type for specific analytics events, allowing for type-safe property access.
 * This ensures that when an event name is known, its specific properties are enforced.
 */
export type AnalyticsEvent =
  | (BaseAnalyticsEvent & { name: 'page_view'; properties: PageViewEventProperties })
  | (BaseAnalyticsEvent & { name: 'click'; properties?: ClickEventProperties })
  | (BaseAnalyticsEvent & { name: 'form_submit'; properties?: FormSubmitEventProperties })
  | (BaseAnalyticsEvent & { name: 'add_to_cart'; properties: AddToCartEventProperties })
  | (BaseAnalyticsEvent & { name: 'purchase'; properties: PurchaseEventProperties })
  // For other specific events in AnalyticsEventName, properties are optional
  | (BaseAnalyticsEvent & {
      name: Exclude<
        AnalyticsEventName,
        'page_view' | 'click' | 'form_submit' | 'add_to_cart' | 'purchase'
      >;
      properties?: AnalyticsProperties;
    })
  // Fallback for any custom string event name not explicitly listed in AnalyticsEventName
  | (BaseAnalyticsEvent & { name: string; properties?: AnalyticsProperties });

/**
 * The full payload structure for sending analytics data to a backend.
 * It can contain multiple events, user information, and global context.
 */
export interface AnalyticsPayload {
  /**
   * An array of analytics events to be sent.
   */
  events: AnalyticsEvent[];
  /**
   * Information about the user performing the events.
   */
  user?: AnalyticsUser;
  /**
   * Global context information for all events in the payload.
   */
  context?: AnalyticsContext;
  /**
   * A unique identifier for the batch of events.
   */
  batchId?: string;
  /**
   * The timestamp when this payload was generated/sent.
   */
  sentAt?: string | number;
}

/**
 * Utility type to extract properties for a specific event name.
 * This helps ensure type safety when defining a `track` function.
 * @template TEventName The name of the event.
 */
export type EventProperties<TEventName extends AnalyticsEventName | string> =
  TEventName extends 'page_view'
    ? PageViewEventProperties
    : TEventName extends 'click'
    ? ClickEventProperties
    : TEventName extends 'form_submit'
    ? FormSubmitEventProperties
    : TEventName extends 'add_to_cart'
    ? AddToCartEventProperties
    : TEventName extends 'purchase'
    ? PurchaseEventProperties
    : AnalyticsProperties; // Default for other events or custom strings

/**
 * A type representing the function signature for tracking an analytics event.
 * @param eventName The name of the event to track.
 * @param properties Optional properties associated with the event. For some events
 *                   (e.g., 'page_view', 'add_to_cart', 'purchase'), these properties
 *                   are mandatory and type-checked.
 * @param options Optional tracking options (e.g., timestamp override, event ID).
 */
export type TrackFunction = <TEventName extends AnalyticsEventName | string>(
  eventName: TEventName,
  properties: TEventName extends 'page_view' | 'add_to_cart' | 'purchase'
    ? EventProperties<TEventName> // Mandatory properties for these specific events
    : EventProperties<TEventName> | undefined, // Optional properties for others
  options?: { timestamp?: string | number; eventId?: string }
) => void;

/**
 * A type representing the function signature for identifying a user.
 * @param user The user object with an ID and optional properties.
 */
export type IdentifyFunction = (user: AnalyticsUser) => void;

/**
 * A type representing the function signature for setting global context properties.
 * These properties will be merged with existing context and sent with subsequent events.
 * @param context The context object to merge with existing context.
 */
export type SetContextFunction = (context: Partial<AnalyticsContext>) => void;

/**
 * A type representing the main analytics client interface.
 * This interface defines the core methods for interacting with an analytics system.
 */
export interface AnalyticsClient {
  /**
   * Tracks an analytics event.
   */
  track: TrackFunction;
  /**
   * Identifies the current user.
   */
  identify: IdentifyFunction;
  /**
   * Sets global context properties for subsequent events.
   */
  setContext: SetContextFunction;
  /**
   * Clears the current user identification.
   */
  clearUser: () => void;
  /**
   * Clears the current session and context.
   */
  clearContext: () => void;
}