/**
 * src/types/api.ts
 *
 * General TypeScript types for API request/response structures.
 * This file defines common patterns for API communication, including
 * success/error responses, pagination, and base resource structures.
 */

/**
 * Represents a successful API response structure.
 * @template T The type of the data returned by the API.
 */
export interface ApiResponse<T> {
  /** Indicates that the API request was successful. */
  success: true;
  /** The actual data returned by the API. */
  data: T;
  /** An optional message providing more context about the success. */
  message?: string;
}

/**
 * Represents an error detail object within an API error response.
 */
export interface ApiErrorDetail {
  /** A unique code identifying the type of error (e.g., 'VALIDATION_ERROR', 'NOT_FOUND'). */
  code: string;
  /** A human-readable message describing the error. */
  message: string;
  /** Optional additional details about the error, often used for validation errors. */
  details?: Record<string, any>;
}

/**
 * Represents an API response structure for an error.
 */
export interface ApiErrorResponse {
  /** Indicates that the API request failed. */
  success: false;
  /** The error object containing details about the failure. */
  error: ApiErrorDetail;
  /** An optional general message about the error, which might be a summary of `error.message`. */
  message?: string;
}

/**
 * A union type representing the possible outcomes of an API call: either a successful response or an error response.
 * @template T The expected type of data in a successful response.
 */
export type ApiResult<T> = ApiResponse<T> | ApiErrorResponse;

/**
 * Represents common query parameters for paginated API requests.
 */
export interface PaginationQueryParams {
  /** The page number to retrieve (1-indexed). */
  page?: number;
  /** The maximum number of items per page. */
  limit?: number;
  /** Optional search term to filter results. */
  search?: string;
  /** Optional field to sort by. */
  sortBy?: string;
  /** Optional sort order ('asc' or 'desc'). */
  sortOrder?: 'asc' | 'desc';
}

/**
 * Represents the metadata for a paginated API response.
 */
export interface PaginationMeta {
  /** The current page number. */
  page: number;
  /** The number of items per page. */
  limit: number;
  /** The total number of items available across all pages. */
  totalItems: number;
  /** The total number of pages available. */
  totalPages: number;
  /** The number of items returned in the current page. */
  itemCount: number;
  /** The URL for the next page, if available. */
  nextPage?: string;
  /** The URL for the previous page, if available. */
  prevPage?: string;
}

/**
 * Represents a successful API response structure for paginated data.
 * @template T The type of the individual items in the paginated list.
 */
export interface PaginatedResponse<T> extends ApiResponse<T[]> {
  /** Metadata related to the pagination. */
  meta: PaginationMeta;
}

/**
 * Base interface for any resource that has a unique identifier.
 */
export interface Identifiable {
  /** The unique identifier of the resource. */
  id: string;
}

/**
 * Base interface for any resource that has creation and update timestamps.
 */
export interface Timestamped {
  /** The ISO 8601 timestamp when the resource was created. */
  createdAt: string;
  /** The ISO 8601 timestamp when the resource was last updated. */
  updatedAt: string;
}

/**
 * A common base interface for most API resources, combining identification and timestamps.
 */
export interface BaseResource extends Identifiable, Timestamped {}

// --- Example API Entities and Operations ---

/**
 * Represents a User entity in the API.
 */
export interface IUser extends BaseResource {
  name: string;
  email: string;
  role: 'admin' | 'user' | 'guest';
  isActive: boolean;
}

/**
 * Represents a Product entity in the API.
 */
export interface IProduct extends BaseResource {
  name: string;
  description: string;
  price: number;
  stock: number;
  category: string;
  imageUrl?: string;
}

// --- Example Request/Response Types for Users ---

/**
 * Query parameters for fetching a list of users.
 */
export interface GetUsersRequestParams extends PaginationQueryParams {
  /** Filter users by role. */
  role?: IUser['role'];
  /** Filter users by active status. */
  isActive?: boolean;
}

/**
 * Response type for fetching a list of users.
 */
export type GetUsersResponse = PaginatedResponse<IUser>;

/**
 * Response type for fetching a single user.
 */
export type GetUserResponse = ApiResponse<IUser>;

/**
 * Payload for creating a new user.
 * Excludes `id`, `createdAt`, `updatedAt` as these are typically generated by the server.
 */
export type CreateUserRequestPayload = Omit<IUser, keyof BaseResource>;

/**
 * Response type after creating a user.
 */
export type CreateUserResponse = ApiResponse<IUser>;

/**
 * Payload for updating an existing user.
 * Allows partial updates and excludes server-generated fields.
 */
export type UpdateUserRequestPayload = Partial<Omit<IUser, keyof BaseResource>>;

/**
 * Response type after updating a user.
 */
export type UpdateUserResponse = ApiResponse<IUser>;

/**
 * Response type after deleting a user.
 */
export type DeleteUserResponse = ApiResponse<{ id: string; message: string }>;

// --- Example Request/Response Types for Products ---

/**
 * Query parameters for fetching a list of products.
 */
export interface GetProductsRequestParams extends PaginationQueryParams {
  /** Filter products by category. */
  category?: string;
  /** Filter products by price range (min). */
  minPrice?: number;
  /** Filter products by price range (max). */
  maxPrice?: number;
  /** Filter products by stock availability. */
  inStock?: boolean;
}

/**
 * Response type for fetching a list of products.
 */
export type GetProductsResponse = PaginatedResponse<IProduct>;

/**
 * Response type for fetching a single product.
 */
export type GetProductResponse = ApiResponse<IProduct>;

/**
 * Payload for creating a new product.
 * Excludes `id`, `createdAt`, `updatedAt` as these are typically generated by the server.
 */
export type CreateProductRequestPayload = Omit<IProduct, keyof BaseResource>;

/**
 * Response type after creating a product.
 */
export type CreateProductResponse = ApiResponse<IProduct>;

/**
 * Payload for updating an existing product.
 * Allows partial updates and excludes server-generated fields.
 */
export type UpdateProductRequestPayload = Partial<Omit<IProduct, keyof BaseResource>>;

/**
 * Response type after updating a product.
 */
export type UpdateProductResponse = ApiResponse<IProduct>;

/**
 * Response type after deleting a product.
 */
export type DeleteProductResponse = ApiResponse<{ id: string; message: string }>;